import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data } = api.projects.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Marcos Capistrano</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <div className="absolute top-0 left-0 bg-[#efefef] w-2/12 h-full z-[-1]">
      </div> */}

      <main className="max-w-[1366px] mx-auto p-4 mt-8">
        <span className="
          font-light
          text-xl
          pl-2
        ">Olá, me chamo</span>
        <h1 className="font-bold text-8xl leading-[0.9]">Marcos <br /> Capistrano</h1>
        <p className="mt-14 w-2/3 text-2xl text-zinc-600">Desde pequeno apaixonado pelo ofício de criação de software para diversas necessidades.
          Atuando profissionalmente há 4 anos em startups em ambientes competitivos e ágeis, que proporcionaram a
          experiência de contato direto com clientes, identificar suas necessidades, e fornecer as soluções necessárias.</p>

        <h2 className="text-6xl font-bold mt-16 mb-10">Projetos</h2>
        {data?.map(project => (
          <div key={project.id} className="flex mb-8 gap-4">
            <Image src={project.imageUrl} alt="project image" width={400} height={400} />
            <div className="flex flex-col gap-4">
              <h3 className="text-4xl font-medium">{project.title}</h3>
              <p className="text-lg mb-2">{project.description}</p>


              <Link href={project.destUrl} className="rounded-md border-black border-2 w-fit p-4">Saiba Mais</Link>
            </div>
          </div>
        ))}
      </main>
    </>
  );
};

export default Home;